### ISSUE TITLE
Questions for John and the team

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/PsyNeuLinkView#27]
1. As previous discussed we will represents only the executable nodes, in order to do that for the compositions we will call the show graph method in order to get all the information we need for the graphical representations. Do the mechanism have an equivalent? If not we will use the json_summary method to get the needed information and we provide these to the frontend.

2. About projections, it seems that the pathway addition methods and the explicit creation of the required projection are interchangeable, is there any preference for the python code generated by the UI?

3. So far the simulation is still a python command in the form of 
```composition.run(etc)``` 
that is happended at the end of the python model/script, however, this is working on the assumption that we run always and only the highest possible composition in the hierarchy tree (at least in the example shown so far), where instead Jon said that we have multiple executable nodes (outer composition, nested compositions, single mechanisms).
Should we run each executable components in the current python context without creating a python instruction for the run or should we attach each run instruction at the bottom of the script?

4. The results are shown as an array of results, how should we display these to the user through the UI?

5. We need to start thinking about the plot configuration from the UI points of view.

**Comment by jrmartin** [comment]
@ddelpiano I'm not sure these answers the questions, I asked today during our call.

1) Mechanism:   There doesn't seem to be an equivalent to composition.show_graph(). PsyneuLink team says json_summary doesn't have all the information. If no information is given, then we can use default black oval for the shapes. 
Composition : show_graph

2) The preference is pathway addition code where it can be infer, otherwise explicit creation.

**Comment by ddelpiano** [comment]
@jrmartin I added more questions in the description, thx

**Comment by ddelpiano** [comment]
projections can be presents (as mechanisms) outside a composition, what api method should we use in order to get the graphviz data representation of each projection? (fyi, _show_structure does not exists for projections).
