### ISSUE TITLE
Projections styling

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/PsyNeuLinkView#31]
as per title, projections needs to be styled as per mockups.

As starting point please branch from feature/30.
The widget used for the projections is now specified in the [componentsMap](https://github.com/MetaCell/PsyNeuLinkView/blob/378216028af44971e043d4d66adf40d70c28c791/src/components/Main.js#L45), so feel free to apply the styling to the component [here](https://github.com/MetaCell/PsyNeuLinkView/blob/feature/30/src/components/custom-node/CustomLinkWidget.js)

**Comment by vidhyalongani** [comment]
@ddelpiano hey, as discussed i am pushing the updates for this one to branch feature/32. If you could look at the position points for the arrow head, it would be great.
If I get some better path coordinates, both for the line  and the arrow head svg, it can look pretty similar to figma like this
<img width="298" alt="Screen Shot 2022-08-02 at 4 30 23 PM" src="https://user-images.githubusercontent.com/71261494/182400467-440eb26b-728f-4e77-b22b-01b94a48ca1b.png">

But with current line svg coordinates and some custom value coordinates for arrow head it looks like this.
<img width="291" alt="Screen Shot 2022-08-02 at 4 19 56 PM" src="https://user-images.githubusercontent.com/71261494/182400702-954952ff-9cb2-4a36-9b90-9e71137561dd.png">
